#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonoAndroidDemo.Resource", IsApplication=true)]

namespace MonoAndroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aztec = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int codabar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int code_128 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int code_39 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int code_93 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int data_matrix = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ean_13 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ean_8 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int itf = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pdf_417 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int qr_code = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int upc_a = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int upc_e = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonDecoderAppSample = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int buttonDecoderChooseExisting = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int buttonDecoderTakeNew = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int buttonEncoderGenerate = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int buttonEncoderSaveBarcode = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int imageViewDecoderBarcode = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int imageViewEncoderBarcode = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textEncoderValue = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int textViewDecoderResult = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int textViewEncoderMsg = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DecoderActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EncoderActivityLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
